# -*- coding: utf-8 -*-
"""exercicio com funcao

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hY9QrMupj82Fo29r515qx05etI4oqTjI

1- ler uma lista de 5 numeros inteiros e mostre cada numero juntamente com sua posicao na lista
"""

def lista1 (lista):
  print(lista)
a = [1,2,3,4,5,6,7]
# print(a[0])

for i in a:
  print(a[i-1]), print(index(a))

"""2- ler uma lista de 10 numeros reais e mostre-os na ordem inversa que foram lidos."""

lista = (10,9,8,7,6,5,4,3,2,1)

for num in (lista):
  print(lista[::-1])
  break

"""3-ler uma lista com 5 idades e exibir a maior e a menor."""

idade = [22,18,19,20,15]

for i in (idade):
  print(max(idade))
  print(min(idade))
  break

"""4-inicialize uma lista de 10 numeros inteiros.Armazene os numeros pares em uma lista PAR e os numeros impares em uma lista IMPAR.
imprima as PAR e IMPAR.
"""

lista_numeros = [1,3,4,5,7,8,10,15,77,90]
pares = []
impares = []

for num in lista_numeros:
  if num %2 == 0:
   pares.append(num)
  else:
   impares.append(num)

print("numeros pares sao ",pares)
print("numeros imapares sao",impares)

"""5- escreva um programa que troque o primeiro com o ultimo elemento de uma lista qualquer ?

"""

lista = [3,5,6,7,5,4,25,66,74,92]

if len(lista) >= 2:
   lista[0], lista[-1] = lista[-1], lista[0]

print(lista)

"""6-qual a saida/resultado da seguinte compreensao de lista?"""



"""7. Considere que você recebe um dicionário contendo informações sobre produtos em
uma loja. Cada chave do dicionário é o nome de um produto e cada valor é uma tupla
contendo o preço e a quantidade em estoque desse produto.
produtos = {
'camiseta': (25.00, 10),
'calça': (45.00, 5),
'sapato': (60.00, 3),
'boné': (15.00, 8)
}
Você deve criar um programa em Python que solicite ao usuário que insira um preço
máximo. Em seguida, o programa deve imprimir os produtos cujo preço seja menor ou
igual ao preço máximo inserido pelo usuário.
"""

produtos = {'camiseta': (25.00, 10),'calça': (45.00, 5),'sapato': (60.00, 3),'boné': (15.00, 8),}
preco_maximo = float(input("digite o preco maximo? "))

for produto in produtos:
    preco = produtos[produto]
    if produtos <= preco_maximo:
     print(f"{produtos}")

"""8-Em uma competição de ginástica, cada atleta recebe votos de sete jurados. A melhor e a pior nota são eliminadas. A sua nota fica sendo a média dos votos restantes. Você deve fazer um programa que receba o nome do ginasta e as notas dos sete jurados alcançadas pelo atleta em sua apresentação e depois informe a sua média, conforme a descrição acima informada (retirar o melhor e o pior salto e depois calcular a média com as notas restantes). As notas não são informadas em ordem crescente ou decrescente."""

ginasta = input("digite o nome do ginasta? ")
notas = []
for quant in range(7):
  notas.append(float(input("digite as notas do ginasta? ")))
  print(notas)

notas.remove(max(notas))
notas.remove(min(notas))


media = sum(notas)/len(notas)
print(f"o {ginasta} recebeu uma media de notas de {media} ")

def areatriangulo(a, b):
  print((a*b)/2)

area = float(input("area: "))
altura = float(input("altura: "))

print("a area do triangulo e",areatriangulo(area,altura))

numeros = []
for numero in numeros:
  numero = int(input("digite um numero:" ))
  numero.append(numeros)